# server
server:
  port: 8080

# dir
dir:
  # static file dir
  static: /static
  module: /module
  css: /static/css

# engine
engine:
  # can be css | sass | compass | less | stylus
  css: css

# proxy option
proxy:
  enable: false
  option:
    - origin: /foo/bar/1
      target: http://foo/bar/1
      method: all
    - origin: /foo/bar/1
      target: http://foo/bar/1
      method: post
